In [2]:
# Setup

import pandas as pd
import kagglehub
import os

In [3]:
# Data Loading

path = kagglehub.dataset_download("hibrahimag1/top-1000-twitch-streamers-data-may-2024")
complete_path = os.path.join(path, "datasetV2.csv")
df = pd.read_csv(complete_path)

In [4]:
df.head()

,RANK,NAME,LANGUAGE,TYPE,MOST_STREAMED_GAME,2ND_MOST_STREAMED_GAME,AVERAGE_STREAM_DURATION,FOLLOWERS_GAINED_PER_STREAM,AVG_VIEWERS_PER_STREAM,AVG_GAMES_PER_STREAM,TOTAL_TIME_STREAMED,TOTAL_FOLLOWERS,TOTAL_VIEWS,TOTAL_GAMES_STREAMED,ACTIVE_DAYS_PER_WEEK,MOST_ACTIVE_DAY,DAY_WITH_MOST_FOLLOWERS_GAINED
0,1,kaicenat,English,personality,Just Chatting,I'm Only Sleeping,7.6,18405,15852,2.3,4698,10600000,9150000,194,3.6,Friday,Saturday
1,2,jynxzi,English,personality,Tom Clancy's Rainbow Six Siege,NBA 2K20,5.4,3386,1145,1.2,8407,5760000,1950000,54,5.6,Tuesday,Sunday
2,3,caedrel,English,personality,League of Legends,I'm Only Sleeping,6.3,689,12331,1.3,6728,797000,14200000,111,2.8,Thursday,Sunday
3,4,caseoh_,English,personality,NBA 2K23,Just Chatting,4.6,7185,0,3.6,2554,4220000,53,385,6.2,Friday,Monday
4,5,ibai,Spanish,personality,Just Chatting,League of Legends,4.1,8289,190714,1.5,6865,15600000,359000000,149,4.3,Wednesday,Saturday

In [5]:
df.shape

(999, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   RANK                            999 non-null    int64
 1   NAME                            999 non-null    object
 2   LANGUAGE                        999 non-null    object
 3   TYPE                            999 non-null    object
 4   MOST_STREAMED_GAME              999 non-null    object
 5   2ND_MOST_STREAMED_GAME          922 non-null    object
 6   AVERAGE_STREAM_DURATION         999 non-null    float64
 7   FOLLOWERS_GAINED_PER_STREAM     999 non-null    int64
 8   AVG_VIEWERS_PER_STREAM          999 non-null    int64
 9   AVG_GAMES_PER_STREAM            999 non-null    float64
 10  TOTAL_TIME_STREAMED             999 non-null    int64
 11  TOTAL_FOLLOWERS                 999 non-null    int64
 12  TOTAL_VIEWS                     999 non-null    int64
 13  TOTAL_GAMES_STREAMED            999 non-null    int64
 14  ACTIVE_DAYS_PER_WEEK            999 non-null    float64
 15  MOST_ACTIVE_DAY                 999 non-null    object
 16  DAY_WITH_MOST_FOLLOWERS_GAINED  999 non-null    object
dtypes: float64(3), int64(7), object(7)
memory usage: 132.8+ KB

In [7]:
df.isnull().sum()

RANK                               0
NAME                               0
LANGUAGE                           0
TYPE                               0
MOST_STREAMED_GAME                 0
2ND_MOST_STREAMED_GAME            77
AVERAGE_STREAM_DURATION            0
FOLLOWERS_GAINED_PER_STREAM        0
AVG_VIEWERS_PER_STREAM             0
AVG_GAMES_PER_STREAM               0
TOTAL_TIME_STREAMED                0
TOTAL_FOLLOWERS                    0
TOTAL_VIEWS                        0
TOTAL_GAMES_STREAMED               0
ACTIVE_DAYS_PER_WEEK               0
MOST_ACTIVE_DAY                    0
DAY_WITH_MOST_FOLLOWERS_GAINED     0
dtype: int64

In [8]:
df.describe()

,RANK,AVERAGE_STREAM_DURATION,FOLLOWERS_GAINED_PER_STREAM,AVG_VIEWERS_PER_STREAM,AVG_GAMES_PER_STREAM,TOTAL_TIME_STREAMED,TOTAL_FOLLOWERS,TOTAL_VIEWS,TOTAL_GAMES_STREAMED,ACTIVE_DAYS_PER_WEEK
count,999.000000,999.000000,999.000000,999.000000,999.000000,999.000000,9.990000e+02,9.990000e+02,999.000000,999.000000
mean,500.972973,5.996697,3383.445445,19595.082082,1.477878,6504.741742,9.194033e+05,3.001478e+07,141.707708,3.591391
std,288.576373,3.241013,2742.696216,43241.584073,0.575189,6731.164111,1.725451e+06,6.280328e+07,245.930466,1.797796
min,1.000000,1.200000,-4240.000000,0.000000,1.000000,27.000000,0.000000e+00,0.000000e+00,1.000000,0.000000
25%,251.500000,4.200000,1360.500000,1726.000000,1.100000,2065.500000,1.875000e+05,6.455000e+05,16.000000,2.200000
50%,501.000000,5.400000,2450.000000,6393.000000,1.300000,4756.000000,4.370000e+05,6.950000e+06,55.000000,3.800000
75%,750.500000,6.900000,4831.500000,20103.000000,1.700000,8871.000000,8.895000e+05,3.015000e+07,168.000000,5.100000
max,1000.000000,23.900000,18889.000000,481615.000000,9.300000,90920.000000,1.900000e+07,5.720000e+08,2980.000000,7.000000

In [9]:
df['MOST_STREAMED_GAME'].value_counts().head(10)

MOST_STREAMED_GAME
Just Chatting         257
League of Legends      84
Grand Theft Auto V     74
VALORANT               60
Casino                 36
Fortnite               35
Dota 2                 35
Counter-Strike         31
Minecraft              24
Virtual Casino         23
Name: count, dtype: int64